import type { DemoTourStep } from "./types";

/** Guided tour through the real app (read-only clinic demo). */
export const APP_DEMO_STEPS: DemoTourStep[] = [
  {
    id: "welcome",
    route: "/dashboard",
    titleKey: "steps.welcome.title",
    bodyKey: "steps.welcome.body",
    placement: "center",
  },
  {
    id: "navigation",
    route: "/dashboard",
    target: '[data-tour="main-nav"]',
    titleKey: "steps.navigation.title",
    bodyKey: "steps.navigation.body",
    placement: "bottom",
  },
  {
    id: "dashboard-hero",
    route: "/dashboard",
    target: '[data-tour="dashboard-hero"]',
    titleKey: "steps.dashboardHero.title",
    bodyKey: "steps.dashboardHero.body",
    placement: "bottom",
  },
  {
    id: "dashboard-tabs",
    route: "/dashboard",
    target: '[data-tour="dashboard-tabs"]',
    titleKey: "steps.dashboardTabs.title",
    bodyKey: "steps.dashboardTabs.body",
    placement: "bottom",
  },
  {
    id: "clients",
    route: "/clients",
    target: '[data-tour="page-header"]',
    titleKey: "steps.clients.title",
    bodyKey: "steps.clients.body",
    placement: "bottom",
  },
  {
    id: "clients-list",
    route: "/clients",
    target: '[data-tour="clients-list"]',
    titleKey: "steps.clientsList.title",
    bodyKey: "steps.clientsList.body",
    placement: "top",
    optional: true,
  },
  {
    id: "pets",
    route: "/pets",
    target: '[data-tour="page-header"]',
    titleKey: "steps.pets.title",
    bodyKey: "steps.pets.body",
    placement: "bottom",
  },
  {
    id: "pets-kpis",
    route: "/pets",
    target: '[data-tour="pets-kpis"]',
    titleKey: "steps.petsKpis.title",
    bodyKey: "steps.petsKpis.body",
    placement: "bottom",
    optional: true,
  },
  {
    id: "pets-dossier",
    route: "/pets",
    target: '[data-tour="pets-list"]',
    titleKey: "steps.petsDossier.title",
    bodyKey: "steps.petsDossier.body",
    placement: "top",
    optional: true,
  },
  {
    id: "dossier-import",
    route: "/import/dossier",
    target: '[data-tour="import-dossier"]',
    titleKey: "steps.dossierImport.title",
    bodyKey: "steps.dossierImport.body",
    placement: "bottom",
  },
  {
    id: "appointments",
    route: "/appointments",
    target: '[data-tour="page-header"]',
    titleKey: "steps.appointments.title",
    bodyKey: "steps.appointments.body",
    placement: "bottom",
  },
  {
    id: "visits",
    route: "/visites",
    target: '[data-tour="page-header"]',
    titleKey: "steps.visits.title",
    bodyKey: "steps.visits.body",
    placement: "bottom",
  },
  {
    id: "consultations",
    route: "/consultations",
    target: '[data-tour="page-header"]',
    titleKey: "steps.consultations.title",
    bodyKey: "steps.consultations.body",
    placement: "bottom",
  },
  {
    id: "consultations-docs",
    route: "/consultations",
    target: '[data-tour="consultations-list"]',
    titleKey: "steps.consultationsDocs.title",
    bodyKey: "steps.consultationsDocs.body",
    placement: "top",
    optional: true,
  },
  {
    id: "vaccinations",
    route: "/vaccinations",
    target: '[data-tour="page-header"]',
    titleKey: "steps.vaccinations.title",
    bodyKey: "steps.vaccinations.body",
    placement: "bottom",
  },
  {
    id: "vaccinations-certs",
    route: "/vaccinations",
    target: '[data-tour="vaccinations-list"]',
    titleKey: "steps.vaccinationsCerts.title",
    bodyKey: "steps.vaccinationsCerts.body",
    placement: "top",
    optional: true,
  },
  {
    id: "antiparasites",
    route: "/antiparasites",
    target: '[data-tour="page-header"]',
    titleKey: "steps.antiparasites.title",
    bodyKey: "steps.antiparasites.body",
    placement: "bottom",
  },
  {
    id: "history",
    route: "/history",
    target: '[data-tour="page-header"]',
    titleKey: "steps.history.title",
    bodyKey: "steps.history.body",
    placement: "bottom",
  },
  {
    id: "history-timeline",
    route: "/history",
    target: '[data-tour="history-timeline"]',
    titleKey: "steps.historyTimeline.title",
    bodyKey: "steps.historyTimeline.body",
    placement: "top",
    optional: true,
  },
  {
    id: "farms",
    route: "/farms",
    target: '[data-tour="page-header"]',
    titleKey: "steps.farms.title",
    bodyKey: "steps.farms.body",
    placement: "bottom",
    optional: true,
  },
  {
    id: "stock",
    route: "/stock",
    target: '[data-tour="page-header"]',
    titleKey: "steps.stock.title",
    bodyKey: "steps.stock.body",
    placement: "bottom",
    optional: true,
  },
  {
    id: "accounting",
    route: "/accounting",
    target: '[data-tour="page-header"]',
    titleKey: "steps.accounting.title",
    bodyKey: "steps.accounting.body",
    placement: "bottom",
    optional: true,
  },
  {
    id: "team",
    route: "/admin/team",
    target: '[data-tour="team-page"]',
    titleKey: "steps.team.title",
    bodyKey: "steps.team.body",
    placement: "bottom",
    optional: true,
  },
  {
    id: "settings",
    route: "/settings",
    target: '[data-tour="page-header"]',
    titleKey: "steps.settings.title",
    bodyKey: "steps.settings.body",
    placement: "bottom",
    optional: true,
  },
  {
    id: "mobile-nav",
    route: "/dashboard",
    target: '[data-tour="mobile-nav"]',
    titleKey: "steps.mobileNav.title",
    bodyKey: "steps.mobileNav.body",
    placement: "top",
    mobileOnly: true,
    optional: true,
  },
  {
    id: "finish",
    route: "/dashboard",
    titleKey: "steps.finish.title",
    bodyKey: "steps.finish.body",
    placement: "center",
  },
];
